### ISSUE TITLE
Products Model references itemQuality instead of itemQuantity

### ISSUE THREAD

**Issue by tseven** [signifyd/signifyd-php#1]
Pretty simple fix.

Change both references of "itemQuality" to "itemQuantity" in /lib/Models/Product.php

**Comment by tseven** [comment]
Found another typo, same file:
"itemHeight" should be "itemWeight"

Has this library been tested? Is it ready for public use?

**Comment by rbpotter** [comment]
Thanks for pointing those out. I've checked in the fix, 

This library is early days (0.11 is the current version), and is primarily being built (at the moment) with our Magento 2 plugin in mind.
