### ISSUE TITLE
Version v0.1.3 should be tagged v0.1.3

### ISSUE THREAD

**Issue by rojoangel** [signifyd/signifyd-php#11]
... in order to be recognized as a stable version by composer.

Currently the tag is `0.1.3` but it should be `v0.1.3`.

With the current tag `composer install` yields the following message:

```
The requested package signifyd/signifyd-php ^0.1.3 exists as signifyd/signifyd-php[dev-SDK, dev-master, v0.1.0, v0.1.1, v0.1.2] but these are rejected by your constraint.
```

**Comment by chrismorris528** [comment]
made a typo, just updated
