### ISSUE TITLE
Packagist/composer not pulling 0.1.6

### ISSUE THREAD

**Issue by Silarn** [signifyd/signifyd-php#13]
For some reason the latest version is not pulling in properly via composer. It simply removes the package completely unless I peg it to a previous version.

**Comment by pedrocasado** [comment]
Looks like the tag is 0.1.6 but it should be v0.1.6.

https://packagist.org/packages/signifyd/signifyd-php

**Comment by chrismorris528** [comment]
The tag in git is v0.1.6. I'll see if we can force push the latest release.

**Comment by chrismorris528** [comment]
Fixed - packagist was using the version number in composer instead of from the tags of the release.
