### ISSUE TITLE
Last version 0.1.6 doesn't install from composer

### ISSUE THREAD

**Issue by galillei** [signifyd/signifyd-php#14]
We try install from composer latest version (0.1.6) but couldn't. Seem's its occur throw this line in composer.json - "type:metapackage". When we return to 0.1.5 all install properly

**Comment by chrismorris528** [comment]
I'll have the team investigate this.

**Comment by navarr** [comment]
Related, 0.1.6 broke our Magento deployment scripts during compilation.  I'm guessing it being marked as a metapackage is keeping the library files from being found by the autoloader, as it's failing to fine the SignifydSettings class:

```Compilation was started.
%message% 0/7 [>---------------------------]   0% 1 sec 66.0 MiB%message% 0/7 [>---------------------------]   0% 1 sec 66.0 MiBProxies code generation... 0/7 [>---------------------------]   0% 1 sec 66.0 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% 1 sec 68.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 68.0 MiB
Fatal error: Class 'Signifyd\Core\SignifydSettings' not found in ./vendor/signifyd/module-connect/Helper/SignifydSettingsMagento.php on line 12
```

**Comment by chrismorris528** [comment]
Sorry about the issue. We just changed the type back to "library" and pushed a new version. Let me know if that resolves it.
