### ISSUE TITLE
How to use validate webhook request inside Laravel

### ISSUE THREAD

**Issue by jofomah** [signifyd/signifyd-php#18]
I am using this package inside a Laravel app, i want to validate webhook request, in Laravel , you can get request body using `$request->getContents()`, $request->all()`, `$request->all()` returns PHP array which i `json_encode`'s and passes to https://github.com/signifyd/signifyd-php/blob/master/lib/Core/SignifydAPI.php#L159

Please can you explain, what the structure of $request should be, fields and data type, obviously it should be a string but how is that string generated, from what?

I get wrong hash no matter what i do, it does not match the request header's `X-SIGNIFYD-SEC-HMAC-SHA256`

**Comment by jofomah** [comment]
@cristian-vatca @gbsmith @rbpotter @chrismorris528 Sorry guys for invoking you guys, but i really need help with this, nice package btw

**Comment by chrismorris528** [comment]
@ebanolopes can you help?

**Comment by gbsmith** [comment]
@jofomah, wonder if the raw Signifyd REST API docs might help you here: https://signifydapi.docs.apiary.io/#reference/webhooks
