### ISSUE TITLE
Product Model is missing itemImage field

### ISSUE THREAD

**Issue by rojoangel** [signifyd/signifyd-php#2]
There's a mismatch between the documentation and the implementation for the Product Model.
According to the documentation it should expose an **itemImage** attribute:

```
        {
                "itemId": "1",
                "itemName": "Sparkly sandals",
                "itemUrl": "http://mydomain.com/sparkly-sandals",
                "itemImage": "http://mydomain.com/images/sparkly-sandals.jpeg",
                "itemQuantity": 1,
                "itemPrice": 49.99,
                "itemWeight": 5
            }
```

But the field is missing from the \Signifyd\Models\Product class.
The issue is present in the library version 0.1.2

**Comment by rojoangel** [comment]
I created #5 pull request to address this issue

**Comment by rbpotter** [comment]
Pull looks fine, thank you
