### ISSUE TITLE
Error: Call to undefined method Signifyd\Core\Response\TransactionsResponse::setError()

### ISSUE THREAD

**Issue by khiminrm** [signifyd/signifyd-php#21]
Hi! While testing sending transaction, I've received error:
Error: Call to undefined method Signifyd\Core\Response\TransactionsResponse::setError() in Signifyd\Core\Connection->handleResponse() (line 275 of /var/www/html/vendor/signifyd/signifyd-php/lib/Core/Connection.php)

Maybe TransactionsResponse should extend Response class instead of Model and implement the setError() method? Other classed from Response folder extend Response.

I used such code:
```
$caseApi = new CaseApi(['apiKey' => $this->apiKey]);
 $response = $caseApi->createTransaction($transactions_data);
```
where $transactions_data is array of test values.

**Comment by khiminrm** [comment]
Investigated Connection::handleResponse(). There is a comments:
```
            // The definition is for Response class because all the other response
            // classes extend the Response class
```
So I've created pull request https://github.com/signifyd/php/pull/22 where I fixed TransactionResponse class and also moved duplicated code from all response classes to Response class which is extended by others.

**Comment by ebanolopes** [comment]
Thanks for your collaboration, the modifications to fix this are already on the main branch, however it's not officially tested yet. Use at your own risk. We'll soon release a new version containing this modifications.
