### ISSUE TITLE
Improve SignifydAPI error logging by providing more context

### ISSUE THREAD

**Issue by rojoangel** [signifyd/signifyd-php#4]
Currently when a call to the API results in an error the only information being logged is the HTTP code returned by the server:

```
$this->logError("Returned http error: ".$info['http_code'])
```

Under certain circumstances it is hard to figure out what's the error root cause with just the HTTP code. The logging error message could be easily improved by adding the response returned by the server in order to provide more context.

A couple of examples:
- _when attempting a request with an invalid API key_  
  the error logged is: "Returned http error: 401"  
  whereas the response returned by the server already contains : {"message":"Provided API Key not found."}
- _when attempting a request with an invalid date format_  
  the error logged is: "Returned http error: 400"  
  whereas the response returned by the server already contains: {"errors":{"purchase.createdAt":["Failed to parse field"]}}

**Comment by rbpotter** [comment]
This has been addressed in 0.1.4. Thank you for your feedback (and sorry about the wait)
