### ISSUE TITLE
Mistyped and advice

### ISSUE THREAD

**Issue by hashsup** [signifyd/signifyd-php#7]
Hello,

In Model Product has not sense property $itemHeight, probably you want $itemWeight, right?

IMHO your system lack of a basic feature, the ability to send you not successful transaction, sometime  thelf try many time with different cards until success. 

Perhaps I'm wrong but you don't create fingerprint on client site?I couldn't find yet any signifyd's JS to integrate in our system that send you that information.

Thank you.

**Comment by varunbhoomi** [comment]
We recently released the device fingerprint API even though it was only collected on a few other platforms before. https://www.signifyd.com/docs/api/#/reference/webhooks/manage-webhook-lists.
We will update the library so this information can be passed to us.
